### ISSUE TITLE
Command Line Arguments to overwrite Config

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#18]
read: http://stackoverflow.com/questions/1200054/java-library-for-parsing-command-line-parameters

decide whether to go for: http://commons.apache.org/proper/commons-cli/usage.html or go for: https://github.com/kohsuke/args4j/blob/master/args4j/examples/SampleMain.java

then overright the static fileds in Config.java class. 

While doing this also look at bug #3 and #4

**Comment by lschmelzeisen** [comment]
Commit 35f28cdb131350ae56827092a38f828ebe5c71ec implements new api which combines config file and command line arguments.

Note: Using Apache Commons CLI.
