### ISSUE TITLE
Do absoluate and Continuation Counts of skp, pos and del (normal) sequences

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#25]
Be able to count all sequences in a text that match a certain pattern which is sepcified by the filter. 

In the beginning it would be nice to just include this for small data sets in the current pipeline but for larger data sets we would probably really switching over to just counting the sequences that are being tested. 

So the algorithm probably goes like this. 

1.) read in the test sequences and from them build all possible matches store them in some IndexHashMap<String, Integer> (with all values initially set to 0)
2.) parse the training text for each pattern of interest and increase the value of the pattern by one if it matches the values in the hashset
3.) if defined (write out the values of the hashmap to some folder structure) 

optionally one could have a sorting step when writing stuff out to files having this sorted by counts or lexicographically. Currently I don't see a real need to do that, but this might change over time.

**Comment by lschmelzeisen** [comment]
Continuation counts are implemented with 42f7036618bc5ff5e3cbe79072d860df7c20f7a4 so this enhancement can be considered implemented.

**Comment by renepickhardt** [comment]
don't make backticks around commit hashes see the difference:
no backticks: 42f7036618bc5ff5e3cbe79072d860df7c20f7a4
with backticks `42f7036618bc5ff5e3cbe79072d860df7c20f7a4`
