### ISSUE TITLE
Test the correctness of the new counting mechanism

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#26]
as a quick fix it will be sufficient to compare absoluate counts of skp sequences with the new method with the results from the existing code.

On the long term software tests as mentioned in #8 will be mandatory.

**Comment by renepickhardt** [comment]
we could also have some grep commands to check for some cases. 

in any case we should include some of the boundary cases

**Comment by lschmelzeisen** [comment]
The test `CountingTest` validates our counting method with a method similiar to grepping every sequence. So far it is only implemented for absolute counts though.

**Comment by renepickhardt** [comment]
we need tests for all counts. We walked through small language models by hand and everything looks good, but this needs to be correct.

**Comment by lschmelzeisen** [comment]
Implemented, see #80.
