### ISSUE TITLE
splitting part of speeches at / might be a problem

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#28]
what happens if a word contained a Slash for example the word A/B testing? In this way all the elements in the pos and words array might be confused. One work around would be to let the part of speech tagger create to slashes to the tagged.txt data.

another way are unit tests and comparing POS tags to a TAG vocabulary

**Comment by lschmelzeisen** [comment]
Is actually not a problem in the current implementation, as words are split by spaces and content and pos are split by _the last slash in a word_. So if the input `a/b c` is tagged it will output `a/b/pos_ab c/pos_c`. And then `pos_ab` is the pos for `a/b` and `pos_c` is the pos for `c`.
