### ISSUE TITLE
Tagging stage / option

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#32]
The tagging of data should only be optional. 
therefor we need a tagging stage which creates tagged.txt from training.txt (if tagged.txt does not exist)

but also for the other stages tagged.txt should be used as an input instead of training.txt 
especially in the tagged case. Also if no part of speech tagged input is expected the programm should not used the PatternElement POS and just create 10011 counts and their respective countinuation counts.

**Comment by lschmelzeisen** [comment]
Added with commit b3f785abc1a682f0b3acfd66a5b565a08c7632c4.
