### ISSUE TITLE
delete sequences WHILE aggregating

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#33]
the aggregator task shoul delete the sequence file after aggregation

This is absolute necessary in order to free disc space.

This can be achieved by changing the internal API from iostreams to files. Our logging system would also benefit from this mechanism since the aggregatorTask could output which file it is currently aggregating. This would help if there are any errors to be handled and also to see some progress

**Comment by lschmelzeisen** [comment]
Implemented with commit f28db891ccdc90f32cf01712878822c83c552a65. You just need to set `deleteTempFiles = true` in `config.txt`.
