### ISSUE TITLE
introduce a POS index

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#36]
We have problems for the Aggregator with certain large files which come from not having our own index for part of speech tags: 

Latest when going to 4 grams the software will crash.

```sequences/021$ du -sh *
775M    0
103M    1
0   10
0   2
11G 3
2.2G    4
0   5
0   6
0   7
0   8
0   9

```
```

**Comment by lschmelzeisen** [comment]
A separate pos index is implemented since commit 477f68779091180018c00048d3d94bafdd900500.
