### ISSUE TITLE
<s> and </s> tags

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#38]
we are currently not making proper use of the start and end sentence tags in our evaluation setting. 

This mistake is of minor importance since it will be negligible but we will have to fix this rather soon since people at least expect those tags to work properly.

**Comment by lschmelzeisen** [comment]
IIRC we will not have `<s>` and `</s>` tags in our software?

**Comment by renepickhardt** [comment]
yep we don't support that since we solve the problem differently
