### ISSUE TITLE
fixing the unigram smoothing

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#39]
+1 smoothing is not quite the same as smoothing with a uniform distribution especially when this is not properly normalized.

I also guess with the stable version we will get rid of this problem

**Comment by lschmelzeisen** [comment]
I do not understand this, can you explain it a bit more detailed? Is this still relevant?

**Comment by renepickhardt** [comment]
I think before we used +1 for UNK and we had problems with UNK. As far as I understand this issue becomes irrelevant since we do not support UNK at the moment. If you see it the same way please close.

**Comment by lschmelzeisen** [comment]
No, we do not support UNK. Unseen sequences will just have count zero. I'm closing this now.

IIRC you said you used +1 smoothing on lowest order in the GLM Paper, so we might have to reopen this.
