### ISSUE TITLE
Execute Program if outputdirectory exists

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#61]
the program glmtk-count should not stop execution if the outputrepo exists but rather continue execution

**Comment by lschmelzeisen** [comment]
I disagree. As an outputdir does not have to be specifically specified by an user, it is easy to unintentionally overwrite parsing results from a previous run. So if a user explicitly wants to overwrite he should just delete the directory.

**Comment by lschmelzeisen** [comment]
Ah now I realize what you meant: You want to continue execution from an older state.

**Comment by renepickhardt** [comment]
or at least give me -f = force option because it is annoying to do this
again and again in debugging and development.

On Tue, Jul 8, 2014 at 2:00 PM, Lukas Schmelzeisen <notifications@github.com

**Comment by lschmelzeisen** [comment]
New API deals with this problem in a different way. If outputdir already exists, it tries to continue operation from the previous state.
