### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jhclark** [renepickhardt/generalized-language-modeling-toolkit#63]
Could you stick a License.txt under the root?

I personally like BSD, but this is of course a personal choice for each coder. :)

**Comment by renepickhardt** [comment]
Thanks for the hint. Your are completly right. With the next release on the master branch we will update a license.txt it will most likely be GPL

**Comment by lschmelzeisen** [comment]
Any definity decision on License? I would vote for GPL3.

**Comment by renepickhardt** [comment]
same for me. bsd / apache might also be an option. but I like GPLv3

On Tue, Jan 6, 2015 at 3:31 PM, Lukas Schmelzeisen <notifications@github.com

> wrote:
> 
> Any definity decision on License? I would vote for GPL3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/renepickhardt/generalized-language-modeling-toolkit/issues/63#issuecomment-68871697
> .

## 

## 

www.rene-pickhardt.de
http://www.beijing-china-blog.com/

Skype: rene.pickhardt

mobile: +49 (0)157 / 3730 2422    office: +49 (0) 261 / 287 2765    fax:
+49 (0) 267 / 287 100 2765

china mobile: +86 186 2129 5033

**Comment by lschmelzeisen** [comment]
To conform to GPL we need a line of the form:
`Copyright (C) <year>  <name of author>`

I do not feel comfortable naming either you or me as author here, so what do we write. University of Koblenz-Landau? Year should be 2012-2015 right?

**Comment by lschmelzeisen** [comment]
GLMTK is now licensed under GPLv3.
